alumni/alumni/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

from alumni import settings

urlpatterns = [
    path("", include("login.urls")),
    path('admin/', admin.site.urls),
    path('main/', include("main.urls")),
    path("market/", include("market.urls")),
    path("my_profile/", include("my_profile.urls")),
    path("card_request/", include("card_request.urls")),
    path("map/", include("map.urls")),
    path("mentorship/", include("mentorship.urls")),
    path("donation/", include("donation.urls")),
    path("events/", include("events.urls")),
    path('', include('aichat.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

alumni/map/urls.py
# In map/urls.py
from django.urls import path
from .views import map_view

urlpatterns = [
    path('', map_view, name='map_view'),
]

alumni/my_profile/urls.py
from django.contrib import admin
from django.urls import path
from django.views.generic import TemplateView
from . import views

urlpatterns = [
    path("profile/", views.profile_view, name="profile"),
    path("profile/edit/", views.edit_profile, name="edit_profile"),
]

alumni/login/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models


class Interest(models.Model):
    name = models.CharField(max_length=100, primary_key=True, serialize=False)

    def __str__(self):
        return self.name
    
    
class CustomUserManager(BaseUserManager):
    def create_user(self, email, first_name, last_name, location=None, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        if not first_name:
            raise ValueError('The First name field must be set')
        if not last_name:
            raise ValueError('The Last name field must be set')

        email = self.normalize_email(email)
        user = self.model(email=email, first_name=first_name, last_name=last_name, location=location, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, first_name, last_name, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        return self.create_user(email, first_name, last_name, "Innopolis", password, **extra_fields)
    
class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=30, blank=True)
    last_name = models.CharField(max_length=30, blank=True)
    user_photo = models.ImageField(upload_to='profile_pics/', blank=True)
    alias = models.CharField(max_length=50, blank=True)
    graduation_year = models.IntegerField(null=True, blank=True)
    position = models.CharField(max_length=50, blank=True)
    company = models.CharField(max_length=50, blank=True)
    location = models.CharField(max_length=50, blank=True)
    interests = models.ManyToManyField(Interest, blank=True)
    activities = models.TextField(blank=True, null=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    def __str__(self):
        return self.email 
        

alumni/my_profile/models.py
from django.db import models
from django.contrib.auth import get_user_model

alumni/my_profile/forms.py
from django import forms
from django_select2.forms import Select2TagWidget
from login.models import CustomUser, Interest

class ProfileForm(forms.ModelForm):
    interests = forms.ModelMultipleChoiceField(
        queryset=Interest.objects.all(),
        widget=forms.CheckboxSelectMultiple(attrs={'class' : 'select2'}),
        required=False
    )
    class Meta:
        model = CustomUser
        fields = [
            'user_photo',
            'alias',
            'graduation_year',
            'position',
            'company',
            'location',
            'interests',
        ]
        widgets = {
            'alias': forms.TextInput(attrs={'class': 'form-control'}),
            'graduation_year': forms.NumberInput(attrs={'class': 'form-control'}),
            'position': forms.TextInput(attrs={'class': 'form-control'}),
            'company': forms.TextInput(attrs={'class': 'form-control'}),
            'location': forms.TextInput(attrs={'class': 'form-control'}),
            'interests': Select2TagWidget(attrs={'class': 'form-control'}),
        }

    user_photo = forms.ImageField(required=False)
    graduation_year = forms.IntegerField(required=False)
    position = forms.CharField(required=False)
    company = forms.CharField(required=False)
    location = forms.CharField(required=False)
    activities = forms.CharField(widget=forms.Textarea, required=False)

    

alumni/my_profile/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from login.models import CustomUser
from .forms import ProfileForm
from .services import get_all_users

@login_required
def profile_view(request):
    try:
        user_profile = request.user
    except CustomUser.DoesNotExist:
        user_profile = None
    
    return render(request, 'my_profile/profile.html', {'user_profile': user_profile})


@login_required
def edit_profile(request):
    user_profile = request.user
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            user_profile.save()
            form.save()
            return redirect('profile')
    else:
        form = ProfileForm(instance=request.user)
    
    return render(request, 'my_profile/edit_profile.html', {'form': form, 'user_profile': user_profile})

alumni/my_profile/templates/my_profile/edit_profile.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'my_profile/styles_profile.css' %}">
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" rel="stylesheet" />
{% endblock style %}

<style>
    .scrollable-interests {
        max-height: 200px;
        overflow-y: auto;
        margin-top: 50px;
    }
</style>

{% block title %}
Edit profile
{% endblock title %}

{% block body %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>
    <div class="container">
        <h2>Edit Profile</h2>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="profile">
                <div class="profile-left">
                    <div class="profile-picture">
                        <label for="id_user_photo" style="display: block; margin-bottom: 5px;"></label>
                        <img src="{% if request.user.user_photo %}{{ request.user.user_photo.url }}{% else %}{% static 'my_profile/user_photo.jpg' %}{% endif %}" alt="Profile Picture" style="width: 201px;
                    height: 194px;
                    position: absolute;
                    top: 0.1%;
                    background-color: #D9D9D9;
                    border-radius: 50%;
                ">
                        <input type="file" name="user_photo" id="id_user_photo" value="{{form.user_photo.value}}" style="margin-top: 190px; width: 100%; padding: 5px;">
                    </div>
                    <h3>{{ request.user.first_name }} {{ request.user.last_name }}</h3>
                    <div class="profile-details">
                        <div class="profile-info">
                            <h4>
                                <label for="id_alias">Alias:</label>
                                <input type="text" name="alias" id="id_alias" value="{{ form.alias.value }}" style="width: 170%; height: 25px; border-radius: 7px;">

                                <label for="id_graduation_year">Graduation Year:</label>
                                <input type="number" name="graduation_year" id="id_graduation_year" value="{{ form.graduation_year.value }}" style="width: 170%; height: 25px; border-radius: 7px;">
                                
                                <label for="id_position">Position:</label>
                                <input type="text" name="position" id="id_position" value="{{ form.position.value }}" style="width: 170%; height: 25px; border-radius: 7px;">

                                <label for="id_company">Company:</label>
                                <input type="text" name="company" id="id_company" value="{{ form.company.value }}" style="width: 170%; height: 25px; border-radius: 7px;">
                                
                                <label for="id_location">City:</label>
                                <input type="text" name="location" id="id_location" value="{{ form.location.value }}" style="width: 170%; height: 25px; border-radius: 7px;"></h4>
                        </div>
                    </div>
                </div>
                <div class="profile-right">
                    <div class="section-interests">
                        <h5><label for="id_interests">Interests:</label></h5>
                            <h7><div class="scrollable-interests">
                                {{ form.interests }}
                            </div></h7>

                        
                    </div>
                    <div class="section-activities">
                        <h5>CURRENT ACTIVITIES</h5>
                        <h8>{% if user_profile.activities %}{{user_profile.activities | safe}}{% else %}{% endif %}</h8>
                    </div>
                </div>
            </div>
            <div class="edit-profile-container">
                <button class="edit-profile-button">
                    <a href="{% url 'profile' %}">
                        <h6>Save changes</h6>
                    </a>
                </button>
            </div>
            </form>
        </div>
<div style="height: 200px;"></div>
{% endblock body %}

alumni/my_profile/templates/my_profile/profile.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'my_profile/styles_profile.css' %}">
{% endblock style %}

{% block title %}
My profile
{% endblock title %}

{% block body %}
{% if user.is_authenticated %}
    <div class="container">
        <h2>MY PROFILE</h2>
        <div class="profile">
            <div class="profile-left">
                <div class="profile-picture">
                    <img src="{% if user_profile.user_photo %}{{ user_profile.user_photo.url }}{% else %}{% static 'my_profile/user_photo.jpg' %}{% endif %}" alt="Profile Picture" style="width: 201px;
                    height: 194px;
                    position: absolute;
                    top: 0.1%;
                    background-color: #D9D9D9;
                    border-radius: 50%;
                ">
                </div>
                <h3>{{ request.user.first_name }} {{ request.user.last_name }}</h3>
                <div class="profile-details">
                    <div class="profile-info">
                        <h4>
                            ALIAS: {{user_profile.alias}} <br>
                            
                            GRADUATION YEAR: {{ user_profile.graduation_year }} <br>

                            POSITION: {{ user_profile.position }} <br>

                            COMPANY: {{ user_profile.company }} <br>
                            
                            CITY: {{ user_profile.location }} <br>
                            
                        
                        </h4>
                    </div>
                </div>
            </div>
            <div class="profile-right">
                <div class="section-interests">
                    <h5>INTERESTS</h5>
                    <h7><ul>
                        {% for interest in user_profile.interests.all %}
                            <li>{{ interest.name }}</li>
                        {% empty %}
                            <li>No interests selected.</li>
                        {% endfor %}
                    </ul></h7>
                </div>
                <div class="section-activities">
                    <h5>CURRENT ACTIVITIES</h5>
                    <h8>{% if user_profile.activities %}{{user_profile.activities | safe}}{% else %}{% endif %}</h8>
                </div>
            </div>
        </div>
        <div class="edit-profile-container">
            <button class="edit-profile-button">
                <a href="{% url 'edit_profile' %}">
                    <h6>Edit profile</h6>
                </a>
            </button>
        </div>
    </div>
    {% else %}
        <p>You are not logged in. Please <a href="{% url 'login' %}">login</a></p>
    {% endif %}
<div style="height: 200px;"></div>
{% endblock body %}